#!/bin/bash

repo=stable
app=jenkins
version=1.5.9
workdir=../../kube-dev/cluster-state/jenkins/raw-templates

cd $workdir
rm -rf tmp
mkdir tmp
helm fetch --untar --untardir=./tmp $repo/$app --version $version
helm template --name $app --namespace=default --output-dir . --values values.yaml ./tmp/$app
mv $app/templates/* ./
rm -rf $app
rm -rf tmp