#!/bin/bash

repo=stable
app=heartbeat
version=1.2.0
workdir=../../kube-logging/cluster-state/elastic-stack/raw-manifests/heartbeat

cd $workdir
rm -rf tmp
mkdir tmp
helm fetch --untar --untardir=./tmp $repo/$app --version $version
helm template --name $app --namespace=default --output-dir . --values values.yaml ./tmp/$app
mv $app/templates/* ./
rm -rf $app
rm -rf tmp