#!/bin/bash

repo=stable
app=kube-state-metrics
version=2.2.2
workdir=../../kube-logging/cluster-state/kube-state-metrics/raw-manifests

cd $workdir
rm -rf tmp
mkdir tmp
helm fetch --untar --untardir=./tmp $repo/$app --version $version
helm template --name $app --namespace=default --output-dir . --values values.yaml ./tmp/$app
mv $app/templates/* ./
rm -rf $app
rm -rf tmp