---
# Source: sentry/charts/redis/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: sentry-redis
  labels:
    app: redis
    chart: redis-3.8.1
    release: "sentry"
    heritage: "Tiller"
type: Opaque
data:
  redis-password: "TlYzWThsNndJNg=="