apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: filebeat
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: logging
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: http://bb.alutech-mc.com:8080/scm/as/infra.git
    targetRevision: HEAD
    path: kube-dev/cluster-state/filebeat/raw-manifests
    directory: 
      recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true