master:
  serviceType: ClusterIP
  ingress: 
    enabled: true
    hostName: "jenkins.kube-dev.in.alutech24.com"
  resources:
    requests: 
      cpu: 50m
      memory: 1024Mi
    limits: 
      cpu: 2000m
      memory: 4096Mi
serviceAccountAgent:
  name: jenkins-agent
persistence:
  existingClaim: jenkins
