---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-logging
spec:
  ports:
  - protocol: TCP
    port: 9200
    targetPort: 31920
---
apiVersion: v1
kind: Endpoints
metadata:
  name: elasticsearch-logging
subsets:
  - addresses:
      - ip: 10.100.20.33
    ports:
      - port: 31920