---
# Source: filebeat/templates/serviceaccount.yaml

apiVersion: v1
kind: ServiceAccount
metadata:
  name: filebeat-filebeat
  labels:
    app: "filebeat-filebeat"
    chart: "filebeat-7.3.0"
    heritage: "Tiller"
    release: "filebeat"