filebeatConfig:
  filebeat.yml: |
    filebeat.inputs:
    - type: container
      symlinks: true
      paths: 
        - '/var/lib/docker/containers/*/*.log'
      processors:
      - add_host_metadata: ~
      - add_kubernetes_metadata:
          in_cluster: true
    - type: log
      paths:
      - /var/log/*.log
      - /var/log/syslog
      processors:
      - add_host_metadata: ~
    output.elasticsearch:
      hosts: '${ELASTICSEARCH_HOSTS:elasticsearch-logging:9200}'
    setup.template.settings:
      index.number_of_shards: 1
      index.codec: best_compression