---
# Source: filebeat/templates/configmap.yaml

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-filebeat-config
  labels:
    app: "filebeat-filebeat"
    chart: "filebeat-7.3.0"
    heritage: "Tiller"
    release: "filebeat"
data:
  filebeat.yml: |
    filebeat.inputs:
    - type: container
      symlinks: true
      paths: 
        - '/var/lib/containers/*/*.log'
      processors:
      - add_host_metadata: ~
      - add_kubernetes_metadata:
          in_cluster: true
          default_matchers.enabled: false
          matchers:
          - logs_path:
              logs_path: /var/log/containers/
    - type: log
      paths:
      - /var/log/*.log
      - /var/log/syslog
      processors:
      - add_host_metadata: ~
    output.elasticsearch:
      hosts: '${ELASTICSEARCH_HOSTS:elasticsearch-master:9200}'
    setup.template.settings:
      index.number_of_shards: 1
      index.codec: best_compression