---
# Source: kube-state-metrics/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: kube-state-metrics
    helm.sh/chart: kube-state-metrics-2.2.2
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/instance: kube-state-metrics
  name: kube-state-metrics
imagePullSecrets:
  []
  