---
# Source: sentry/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: sentry
  labels:
    app: sentry
    chart: "sentry-2.0.0"
    release: "sentry"
    heritage: "Tiller"
type: Opaque
data:
  
  sentry-secret: "RWJKZUdmamVGM3VXNlRaNUNEQ0llN0p0VXhMV1ZtTXJIMDhsWjc2Wg=="
  
  smtp-password: "UE84M3JoYi1TSEY="
  
  
  user-password: "WmVTaHRJTXVnT2V5a1pBWQ=="
  
  
  
