---
# Source: sentry/templates/workers-deployment.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sentry-worker
  labels:
    app: sentry
    chart: "sentry-2.0.0"
    release: "sentry"
    heritage: "Tiller"
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        metrics-enabled: "false"
        checksum/configYml: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
        checksum/sentryConfPy: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
      labels:
        app: sentry
        release: "sentry"
        role: worker
    spec:
      containers:
      - name: sentry-workers
        image: "sentry:9.0"
        imagePullPolicy: IfNotPresent
        args:
          - "run"
          - "worker"
        ports:
        - containerPort: 9000
        env:
        - name: SENTRY_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: sentry
              key: sentry-secret
        - name: SENTRY_DB_USER
          value: "sentry"
        - name: SENTRY_DB_NAME
          value: "sentry"
        - name: SENTRY_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sentry-postgresql
              key: postgres-password
        - name: SENTRY_POSTGRES_HOST
          value: sentry-postgresql
        - name: SENTRY_POSTGRES_PORT
          value: "5432"
        - name: SENTRY_REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sentry-redis
              key: redis-password
        - name: SENTRY_REDIS_HOST
          value: sentry-redis-master
        - name: SENTRY_REDIS_PORT
          value: "6379"
        - name: SENTRY_EMAIL_HOST
          value: "owa.alutech-mc.com"
        - name: SENTRY_EMAIL_PORT
          value: "587"
        - name: SENTRY_EMAIL_USER
          value: "alutech\\sap-portal-noreply"
        - name: SENTRY_EMAIL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sentry
              key: smtp-password
        - name: SENTRY_EMAIL_USE_TLS
          value: "true"
        - name: SENTRY_SERVER_EMAIL
          value: "noreply@alutech24.com"
        volumeMounts:
        - mountPath: /etc/sentry
          name: config
          readOnly: true
        - mountPath: /var/lib/sentry/files
          name: sentry-data
        resources:
            limits:
              cpu: 300m
              memory: 1000Mi
            requests:
              cpu: 100m
              memory: 100Mi
            
      volumes:
      - name: config
        configMap:
          name: sentry
      - name: sentry-data
        emptyDir: {}
      
