---
# Source: sentry/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: sentry
  labels:
    app: sentry
    chart: "sentry-2.0.0"
    release: "sentry"
    heritage: "Tiller"
type: Opaque
data:
  
  sentry-secret: "cGZidnpnRlA3clRTdTE4QW5yUG5Bc0F3eFFDUFBzVjR3aUtKcUR5SQ=="
  
  smtp-password: ""
  
  
  user-password: "M3FNcnliN0RDd0M4eG9EaQ=="
  
  
  
