FROM ubuntu:16.04

# Ubuntu Packages
RUN apt update -y && \
  apt install -y sudo \
  libssl-dev python-dev sshpass apt-transport-https \
  ca-certificates curl gnupg2 software-properties-common \
  python-pip curl sshpass
# Ubuntu Packages

# Docker
RUN curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add - && \
  add-apt-repository \
  "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
  $(lsb_release -cs) \
  stable" \
  && apt update -y && apt-get install docker-ce -y
# Docker

# Kubectl
ARG KUBECTL_VERSION=v1.13.2
ENV KUBECTL_URL https://storage.googleapis.com/kubernetes-release/release/${KUBECTL_VERSION}/bin/linux/amd64/kubectl

RUN curl -Lo /tmp/kubectl ${KUBECTL_URL} \
  && chmod +x /tmp/kubectl \
  && mv /tmp/kubectl /usr/bin/kubectl
# Kubectl

# Helm
ARG HELM_VERSION=v2.12.3
ENV HELM_URL https://storage.googleapis.com/kubernetes-helm/helm-${HELM_VERSION}-linux-amd64.tar.gz

RUN curl -Lo /tmp/helm.tar.gz ${HELM_URL} \
  && tar -zxvf /tmp/helm.tar.gz -C /tmp \
  && mv /tmp/linux-amd64/helm /usr/bin/helm \
  && rm -rf /tmp/*
# Helm

# Kubespray
RUN mkdir /kubespray
WORKDIR /kubespray

COPY ./kubespray ./kubespray
COPY ./requirements.txt ./requirements.txt

RUN /usr/bin/python -m pip install pip -U && \
  /usr/bin/python -m pip install -r kubespray/requirements.txt && \
  /usr/bin/python -m pip install -r requirements.txt
# Kubespray

# Copying other stuff besides kubespray
COPY . .

ENTRYPOINT [ "scripts/kubespray-entrypoint.sh" ]