# Source: reportportal/templates/elasticsearch-statefulset.yaml
apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: elasticsearch
  labels:     
    app: "cautious-bison"
spec:
  replicas: 1
  selector:
    matchLabels:
      component: reportportal-elasticsearch
  serviceName: elasticsearch
  template:
    metadata:
      labels:
        component: reportportal-elasticsearch
    spec:
      containers:
      - image: "docker.elastic.co/elasticsearch/elasticsearch-oss:6.1.1"
        name: elasticsearch
        
      nodeSelector:
        runtime: log
      initContainers:
      - image: busybox
        command:
        - sysctl
        - -w
        - vm.max_map_count=262144
        name: elasticsearch-init
        securityContext:
          privileged: true
---

# Source: reportportal/templates/elasticsearch-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:     
    app: "cautious-bison"
spec:
  clusterIP: None
  ports:
  - name: headless
    port: 55555
    protocol: TCP
    targetPort: 55555
  selector:
    component: reportportal-elasticsearch
  type: ClusterIP
---
