- name: List installed Helm charts.
  command: helm list
  register: helm_list_results
  changed_when: False

- name: Install Nginx Ingress Controller.
  command: >
    helm install stable/nginx-ingress
    --namespace kube-system
    --name nginx-ingress
    --version 1.3.1
    -f -
  args:
    stdin: |
      controller:
        replicaCount: 2
        service:
          type: NodePort
          nodePorts:
            http: 32189
        stats:
          enabled: true
        metrics:
          enabled: true
  when: "'nginx-ingress' not in helm_list_results.stdout"
