---
# Source: metricbeat/templates/configmap.yaml

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: metricbeat-metricbeat-config
  labels:
    app: "metricbeat-metricbeat"
    chart: "metricbeat-7.3.0"
    heritage: "Tiller"
    release: "metricbeat"
data:
  kube-state-metrics-metricbeat.yml: |
    metricbeat.modules:
    # State metrics from kube-state-metrics service:
    - module: kubernetes
      enabled: true
      metricsets:
        - state_node
        - state_deployment
        - state_replicaset
        - state_statefulset
        - state_pod
        - state_container
      period: 10s
      hosts: ["${KUBE_STATE_METRICS_HOSTS:kube-state-metrics:8080}"]
      processors:
      - add_kubernetes_metadata:
          in_cluster: true
          labels.dedot: true
          annotations.dedot: true
    output.file:
      path: "/usr/share/metricbeat/data"
      filename: metricbeat
      rotate_every_kb: 10000
      number_of_files: 5    
    # output.elasticsearch:
    #   hosts: '${ELASTICSEARCH_HOSTS:elasticsearch-master:9200}'
    
  metricbeat.yml: |
    system:
      hostfs: /hostfs
    metricbeat.modules:
    # Node metrics, from kubelet:
    - module: kubernetes
      metricsets:
        - container
        - node
        - pod
        - system
        - volume
      period: 10s
      hosts: ["localhost:10255"]
      enabled: true
      add_metadata: true
      in_cluster: true
    
    # Kubernetes events
    - module: kubernetes
      enabled: true
      metricsets:
        - event

    # Kubernetes API server
    - module: kubernetes
      enabled: true
      metricsets:
        - apiserver
      hosts: ["https://${KUBERNETES_SERVICE_HOST}:${KUBERNETES_SERVICE_PORT}"]
      
    # Kubernetes proxy server
    - module: kubernetes
      enabled: true
      metricsets:
        - proxy
      hosts: ["localhost:10249"]
      period: 10s

    # Kubernetes controller manager
    - module: kubernetes
      enabled: true
      metricsets:
        - controllermanager
      hosts: ["http://localhost:10252"]
      period: 10s

    # Kubernetes scheduler
    - module: kubernetes
      enabled: true
      metricsets:
        - scheduler
      hosts: ["localhost:10251"]
      period: 10s

    - module: system
      period: 10s
      metricsets:
        - cpu
        - load
        - memory
        - network
        - process
        - process_summary
      processes: ['.*']
      process.include_top_n:
        by_cpu: 5
        by_memory: 5
    - module: system
      period: 1m
      metricsets:
        - filesystem
        - fsstat
      processors:
      - drop_event.when.regexp:
          system.filesystem.mount_point: '^/(sys|cgroup|proc|dev|etc|host|lib)($|/)'
    output.elasticsearch:
      hosts: '${ELASTICSEARCH_HOSTS:elasticsearch-master:9200}'
    