---
# Source: metricbeat/templates/serviceaccount.yaml

apiVersion: v1
kind: ServiceAccount
metadata:
  name: metricbeat-metricbeat
  labels:
    app: "metricbeat-metricbeat"
    chart: "metricbeat-7.3.0"
    heritage: "Tiller"
    release: "metricbeat"