- name: Install ELK stack.
  command: >
    helm install stable/elastic-stack
    --namespace logging
    --name elk
    --version 1.8.0
    -f -
  args:
    stdin: |
      elasticsearch:
        client: 
          replicas: 1
          serviceType: NodePort
          httpNodePort: 31920
        master:
          persistence:
            storageClass: local-storage
        data:
          replicas: 1
          persistence:
            storageClass: local-storage
      logstash:
        enabled: false
        # elasticsearch:
        #   host: elk-elasticsearch-client
        # persistence:
        #   enabled: false
        # outputs:
        #   main: |-
        #     output {
        #       elasticsearch {
        #         hosts => ["${ELASTICSEARCH_HOST}:${ELASTICSEARCH_PORT}"]
        #         manage_template => false
        #         index => "%{[@metadata][beat]}-%{[@metadata][version]}-%{+YYYY.MM.dd}"
        #       }
        #     }
        # service:
        #   type: NodePort
        #   # TODO: this specific port is not set
        #   nodePort: 31044
      # filebeat:
      #   enabled: true
        # config:
        #   output.file.enabled: false
        #   output.logstash:
        #     hosts: ["elk-logstash:5044"]
        # indexTemplateLoad:
        #   - elk-elasticsearch-client:9200
      kibana:
        files:
          kibana.yml:
            server.name: kibana
            server.host: "0"
            elasticsearch.url: http://elk-elasticsearch-client:9200
        ingress:
          enabled: true
          hosts:
            - "kibana.{{ base_domain }}"
  when: "'elk' not in helm_list_results.stdout"