- name: List installed Helm charts.
  command: helm list
  register: helm_list_results
  changed_when: False

- name: Install Heapster.
  command: >
    helm install stable/heapster
    --namespace kube-system
    --name heapster
    --version 0.3.2
  when: "'heapster' not in helm_list_results.stdout"
