- name: Get helm tiller status
  k8s_facts:
    kind: Deployment
    label_selectors:
      - app = helm
      - name = tiller
    namespace: kube-system
  register: tiller

- name: "Helm init: client + tiller"
  import_tasks: helm-tiller.yml
  when: tiller.resources | length == 0

- name: "Helm init: client only"
  command: helm init --client-only
  when: tiller.resources | length > 0

- name: "Helm repo update"
  command: helm repo update
