- name: Get Jenkins Namespace
  k8s_facts:
    api_version: v1
    kind: Namespace
    name: jenkins
  register: jenkinsNS

- name: Create Jenkins Namespace
  k8s:
    name: jenkins
    api_version: v1
    kind: Namespace
    state: present
  when: jenkinsNS.resources | length == 0

- name: Get Jenkins PV status
  k8s_facts:
    api_version: v1
    kind: PersistentVolume
    name: jenkins
  register: jenkinsPV

- name: Create Jenkins PV if needed
  k8s:
    state: "present"
    definition:
      apiVersion: v1
      kind: PersistentVolume
      metadata:
        name: jenkins
      spec:
        persistentVolumeReclaimPolicy: Retain
        accessModes:
          - ReadWriteMany
        capacity:
          storage: 10Gi
        claimRef:
          apiVersion: v1
          kind: PersistentVolumeClaim
          name: jenkins
          namespace: jenkins
        nfs:
          path: /jenkins
          server: "{{ hostvars[groups['nfs-server'][0]].ansible_host }}"
  when: jenkinsPV.resources | length == 0

- name: Get Jenkins PVC status
  k8s_facts:
    api_version: v1
    kind: PersistentVolumeClaim
    name: jenkins
    namespace: jenkins
  register: jenkinsPVC

- name: Create Jenkins PVC if needed
  k8s:
    state: "present"
    definition:
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: jenkins
        namespace: jenkins
      spec:
        accessModes:
          - ReadWriteMany
        resources:
          requests:
            storage: 10Gi
        volumeName: jenkins
  when: jenkinsPVC.resources | length == 0

- name: List installed Helm charts.
  command: helm list
  register: helm_list_results
  changed_when: False

- name: Create Jenkins Agent service account
  k8s:
    state: "present"
    definition:
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: jenkins-agent
        namespace: jenkins
  when: "'jenkins' not in helm_list_results.stdout"

- name: Make Jenkins Agent a cluster admin
  k8s:
    state: "present"
    definition:
      apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRoleBinding
      metadata:
        name: jenkins-agent
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: cluster-admin
      subjects:
        - kind: ServiceAccount
          name: jenkins-agent
          namespace: jenkins
  when: "'jenkins' not in helm_list_results.stdout"

- name: Create Jenkins Secret with K8S cluster metadata
  k8s:
    state: "present"
    definition:
      apiVersion: v1
      data:
        base_domain: "{{ base_domain | b64encode }}"
      kind: Secret
      metadata:
        name: cluster-metadata
        namespace: jenkins
      type: Opaque
  when: "'jenkins' not in helm_list_results.stdout"

- name: Install Jenkins.
  command: >
    helm install stable/jenkins
    --namespace jenkins
    --name jenkins
    --version 1.1.16
    -f -
  args:
    stdin: |
      master:
        imageTag: 2.164 
        serviceType: ClusterIP
        ingress: 
          enabled: true
          hostName: "jenkins.{{ base_domain }}"
        resources:
          requests: 
            cpu: 50m
            memory: 1024Mi
          limits: 
            cpu: 2000m
            memory: 4096Mi
      serviceAccountAgent:
        name: jenkins-agent
      persistence:
        existingClaim: jenkins
  when: "'jenkins' not in helm_list_results.stdout"
