- name: Get Jenkins Namespace
  k8s_facts:
    api_version: v1
    kind: Namespace
    name: jenkins
  register: jenkinsNS

- name: Create Jenkins Namespace
  k8s:
    name: jenkins
    api_version: v1
    kind: Namespace
    state: present
  when: jenkinsNS.resources | length == 0

- name: Get Jenkins PV status
  k8s_facts:
    api_version: v1
    kind: PersistentVolume
    name: jenkins-1
  register: jenkinsPV

- name: Create Jenkins PV if needed
  k8s:
    state: "present"
    definition:
      apiVersion: v1
      kind: PersistentVolume
      metadata:
        name: jenkins-1
      spec:
        persistentVolumeReclaimPolicy: Retain
        accessModes:
          - ReadWriteMany
        capacity:
          storage: 10Gi
        claimRef:
          apiVersion: v1
          kind: PersistentVolumeClaim
          name: jenkins-1
          namespace: jenkins
        nfs:
          path: /jenkins-1
          server: "{{ hostvars[groups['nfs-server'][0]].ansible_host }}"
  when: jenkinsPV.resources | length == 0

- name: Get Jenkins PVC status
  k8s_facts:
    api_version: v1
    kind: PersistentVolumeClaim
    name: jenkins-1
    namespace: jenkins
  register: jenkinsPVC

- name: Create Jenkins PVC if needed
  k8s:
    state: "present"
    definition:
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: jenkins-1
        namespace: jenkins
      spec:
        accessModes:
          - ReadWriteMany
        resources:
          requests:
            storage: 10Gi
        volumeName: jenkins-1
  when: jenkinsPVC.resources | length == 0

- name: List installed Helm charts.
  command: helm list
  register: helm_list_results
  changed_when: False

- name: Install Jenkins-1.
  command: >
    helm install stable/jenkins
    --namespace jenkins
    --name jenkins-1
    --version 1.1.16
    -f -
  args:
    stdin: |
      master: 
        serviceType: ClusterIP
        ingress: 
          enabled: true
          hostName: jenkins.alutech.local
      serviceAccountAgent:
        name: jenkins-agent
      persistence:
        existingClaim: jenkins-1
  # when: "'jenkins-1' not in helm_list_results.stdout"
