######################################################
# TODO: this is a temporary config. Remove this!!!

- name: Local storage class
  k8s:
    state: "present"
    definition:
      apiVersion: storage.k8s.io/v1
      kind: StorageClass
      metadata:
        name: local-storage
      provisioner: kubernetes.io/no-provisioner
      volumeBindingMode: WaitForFirstConsumer

- name: Local storage PV on "asvc-exp-pool2" node
  k8s:
    state: "present"
    definition:
      apiVersion: v1
      kind: PersistentVolume
      metadata:
        name: asvc-exp-pool2-local-storage
      spec:
        capacity:
          storage: 30Gi
        volumeMode: Filesystem
        accessModes:
        - ReadWriteOnce
        persistentVolumeReclaimPolicy: Retain
        storageClassName: local-storage
        local:
          path: /var/kubernetes-local-storage/elk
        nodeAffinity:
          required:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - asvc-exp-pool2

- name: Local storage PV on "asvc-exp-pool3" node
  k8s:
    state: "present"
    definition:
      apiVersion: v1
      kind: PersistentVolume
      metadata:
        name: asvc-exp-pool3-local-storage
      spec:
        capacity:
          storage: 30Gi
        volumeMode: Filesystem
        accessModes:
        - ReadWriteOnce
        persistentVolumeReclaimPolicy: Retain
        storageClassName: local-storage
        local:
          path: /var/kubernetes-local-storage/elk
        nodeAffinity:
          required:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - asvc-exp-pool3

- name: Local storage PV on "asvc-exp-pool4" node
  k8s:
    state: "present"
    definition:
      apiVersion: v1
      kind: PersistentVolume
      metadata:
        name: asvc-exp-pool4-local-storage
      spec:
        capacity:
          storage: 30Gi
        volumeMode: Filesystem
        accessModes:
        - ReadWriteOnce
        persistentVolumeReclaimPolicy: Retain
        storageClassName: local-storage
        local:
          path: /var/kubernetes-local-storage/elk
        nodeAffinity:
          required:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - asvc-exp-pool4

- name: Local storage PV on "asvc-exp-pool5" node
  k8s:
    state: "present"
    definition:
      apiVersion: v1
      kind: PersistentVolume
      metadata:
        name: asvc-exp-pool5-local-storage
      spec:
        capacity:
          storage: 30Gi
        volumeMode: Filesystem
        accessModes:
        - ReadWriteOnce
        persistentVolumeReclaimPolicy: Retain
        storageClassName: local-storage
        local:
          path: /var/kubernetes-local-storage/elk
        nodeAffinity:
          required:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - asvc-exp-pool5

##############################################################################
############### Sentry #######################################################

- name: Sentry local storage class
  k8s:
    state: "present"
    definition:
      apiVersion: storage.k8s.io/v1
      kind: StorageClass
      metadata:
        name: sentry-storage
      provisioner: kubernetes.io/no-provisioner
      volumeBindingMode: WaitForFirstConsumer

- name: Sentry PV 1 on "asvc-exp-pool2" node
  k8s:
    state: "present"
    definition:
      apiVersion: v1
      kind: PersistentVolume
      metadata:
        name: sentry-pv-1
      spec:
        capacity:
          storage: 10Gi
        volumeMode: Filesystem
        accessModes:
        - ReadWriteOnce
        persistentVolumeReclaimPolicy: Retain
        storageClassName: sentry-storage
        local:
          path: /var/kubernetes-local-storage/sentry/1
        nodeAffinity:
          required:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - asvc-exp-pool2

- name: Sentry PV 2 on "asvc-exp-pool2" node
  k8s:
    state: "present"
    definition:
      apiVersion: v1
      kind: PersistentVolume
      metadata:
        name: sentry-pv-2
      spec:
        capacity:
          storage: 10Gi
        volumeMode: Filesystem
        accessModes:
        - ReadWriteOnce
        persistentVolumeReclaimPolicy: Retain
        storageClassName: sentry-storage
        local:
          path: /var/kubernetes-local-storage/sentry/2
        nodeAffinity:
          required:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - asvc-exp-pool2

- name: Sentry PV 3 on "asvc-exp-pool2" node
  k8s:
    state: "present"
    definition:
      apiVersion: v1
      kind: PersistentVolume
      metadata:
        name: sentry-pv-3
      spec:
        capacity:
          storage: 10Gi
        volumeMode: Filesystem
        accessModes:
        - ReadWriteOnce
        persistentVolumeReclaimPolicy: Retain
        storageClassName: sentry-storage
        local:
          path: /var/kubernetes-local-storage/sentry/3
        nodeAffinity:
          required:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - asvc-exp-pool2

##############################################################################

# TODO: this is a temporary config. Remove this!!!
######################################################
