- name: Set up kube config
  import_tasks: kube-config.yml

- name: Get helm tiller status
  k8s_facts:
    kind: Deployment
    label_selectors:
      - app = helm
      - name = tiller
    namespace: kube-system
  register: tiller

- name: Install helm tiller
  import_tasks: helm-tiller.yml
  vars:
    tiller_state: present
  when: tiller.resources | length == 0

- name: Helm Repo Update.
  command: helm repo update
  changed_when: False

- name: Nginx ingress controller
  import_tasks: nginx-ingress-controller.yml
