- name: Set up kube config
  import_tasks: kube-config.yml

- name: Set up service accounts
  import_tasks: service-accounts-for-the-team.yml

- name: Helm Init
  import_tasks: helm-init.yml

- name: Kubernetes Dashboard
  import_tasks: dashboard.yml

- name: Nginx Ingress Controller
  import_tasks: nginx-ingress-controller.yml

- name: Heapster
  import_tasks: heapster.yml
