- debug:
  var: inventory_dir

- name: Check kube config in user home
  stat:
    path: ~/.kube/config
  register: kube_config

# - name: Check kube config in ansible artifact dir
#   stat:
#     path: ...................
#   register: kube_config_in_ansible

- fail:
    msg: "Kube config is not found at '~/.kube/config'"
  when: kube_config.stat.exists == False

- name: Get helm tiller status
  k8s_facts:
    kind: Deployment
    label_selectors:
      - app = helm
      - name = tiller
    namespace: kube-system
  register: tiller

- name: Install helm tiller
  import_tasks: helm-tiller.yml
  vars:
    tiller_state: present
  when: tiller.resources | length == 0
