- name: Define kube config variables
  vars:
    kube_config_in_home_path: ~/.kube/config
    kube_config_in_ansible_artifacts_path: /kubespray/artifacts/admin.conf

- name: Check kube config in user home
  stat:
    path: "{{ kube_config_in_home_path }}"
  register: kube_config_in_home_stat

- name: Check kube config in ansible artifacts dir
  stat:
    path: "{{ kube_config_in_ansible_artifacts_path }}"
  register: kube_config_in_ansible_stat

#remove
- debug:
  var: kube_config_in_home

- debug:
    var: kube_config_in_ansible
#remove

- fail:
    msg: "Kube config is not found in both '~/.kube/config' and /kubespray/artifacts/admin.conf"
  when: (kube_config_in_home.stat.exists == False and kube_config_in_ansible.stat.exists == False)

  copy:
    src: "{{ kube_config_in_ansible_artifacts_path }}"
    dest: "{{ kube_config_in_home_path }}"
  when: (kube_config_in_home.stat.exists == False and kube_config_in_ansible.stat.exists == True)

- name: Get helm tiller status
  k8s_facts:
    kind: Deployment
    label_selectors:
      - app = helm
      - name = tiller
    namespace: kube-system
  register: tiller

- name: Install helm tiller
  import_tasks: helm-tiller.yml
  vars:
    tiller_state: present
  when: tiller.resources | length == 0
