- name: List installed Helm charts.
  command: helm list
  register: helm_list_results
  changed_when: False

- name: Install nginx ingress controller.
  command: >
    helm install stable/nginx-ingress
    --namespace kube-system
    --name nic
    -f -
  args:
    stdin: |
      controller:
        config:
          ssl-redirect: "false"
        service:
          type: NodePort
  when: "'nginx-ingress' not in helm_list_results.stdout"
  # do prod params, pin nic version
