# Sasha Krasnik's service account
- name: Create service account for Sasha Krasnik
  k8s:
    state: "present"
    definition:
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: alexander-krasnik
        namespace: default

- name: Make Sasha Krasnik a cluster admin
  k8s:
    state: "present"
    definition:
      apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRoleBinding
      metadata:
        name: alexander-krasnik-cluster-admin
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: cluster-admin
      subjects:
        - kind: ServiceAccount
          name: alexander-krasnik
          namespace: default

# Vova Bondar's service account
- name: Create service account for Vova Bondar
  k8s:
    state: "present"
    definition:
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: vladimir-bondar
        namespace: default

- name: Make Vova Bondar a cluster admin
  k8s:
    state: "present"
    definition:
      apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRoleBinding
      metadata:
        name: vladimir-bondar-cluster-admin
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: cluster-admin
      subjects:
        - kind: ServiceAccount
          name: vladimir-bondar
          namespace: default

# Pavel Mikhalchuk's service account
- name: Create service account for Pavel Mikhalchuk
  k8s:
    state: "present"
    definition:
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: pavel-mikhalchuk
        namespace: default

- name: Make Pavel Mikhalchuk a cluster admin
  k8s:
    state: "present"
    definition:
      apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRoleBinding
      metadata:
        name: pavel-mikhalchuk-cluster-admin
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: cluster-admin
      subjects:
        - kind: ServiceAccount
          name: pavel-mikhalchuk
          namespace: default
