---
# Source: sentry/charts/postgresql/templates/deployment.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sentry-postgresql
  labels:
    app: postgresql
    chart: postgresql-0.18.0
    release: sentry
    heritage: Tiller
spec:
  selector:
    matchLabels:
      app: postgresql
      release: sentry
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgresql
        release: sentry
    spec:
      containers:
      - name: sentry-postgresql
        image: "postgres:9.5"
        imagePullPolicy: "IfNotPresent"
        args:
        env:
        - name: POSTGRES_USER
          value: "sentry"
          # Required for pg_isready in the health probes.
        - name: PGUSER
          value: "sentry"
        - name: POSTGRES_DB
          value: "sentry"
        - name: POSTGRES_INITDB_ARGS
          value: ""
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sentry-postgresql
              key: postgres-password
        - name: POD_IP
          valueFrom: { fieldRef: { fieldPath: status.podIP } }
        ports:
        - name: postgresql
          containerPort: 5432
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - exec pg_isready --host $POD_IP
          initialDelaySeconds: 60
          timeoutSeconds: 5
          failureThreshold: 6
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - exec pg_isready --host $POD_IP
          initialDelaySeconds: 5
          timeoutSeconds: 3
          periodSeconds: 5
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data/pgdata
          subPath: postgresql-db
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: sentry-postgresql
