---
# Source: sentry/charts/postgresql/templates/pvc.yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sentry-postgresql
  labels:
    app: postgresql
    chart: postgresql-0.18.0
    release: sentry
    heritage: Tiller
  annotations:
    "helm.sh/resource-policy": nil
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "10Gi"
  storageClassName: "sentry-storage"