---
# Source: sentry/charts/postgresql/templates/secrets.yaml

apiVersion: v1
kind: Secret
metadata:
  name: sentry-postgresql
  labels:
    app: postgresql
    chart: postgresql-0.18.0
    release: sentry
    heritage: Tiller
type: Opaque
data:
  
  postgres-password: "aVV2V2l5YjhwWQ=="
  
