---
apiVersion: v1
kind: ConfigMap
metadata:
  name: heartbeat-config
  labels:
    app: "heartbeat"
data:
  heartbeat.yml: |
    
    heartbeat.config.monitors:
      path: /path/to/my/monitors.d/*.yml
      reload.enabled: true

    heartbeat.monitors:
    - type: http
      name: AService Prod
      schedule: '@every 5s'
      urls: ["https://aservice.alutech24.com/webPortal/"]
      check.response.status: 200
    - type: http
      name: Dealer Prod
      schedule: '@every 5s'
      urls: ["https://dealer.alutech24.com/"]
      check.response.status: 302
    - type: http
      name: Manager Prod
      schedule: '@every 5s'
      urls: ["https://manager.alutech24.com/"]
      check.response.status: 302
    - type: http
      name: Auth Prod
      schedule: '@every 5s'
      urls: ["https://auth.alutech24.com/cas/login/"]
      check.response.status: 200

    output.elasticsearch:
      hosts: '${ELASTICSEARCH_HOSTS:elasticsearch-master:9200}'
    
    setup.kibana:
      host: '${KIBANA_HOST:kibana-kibana:5601}'
