---
# Source: heartbeat/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: heartbeat
  labels:
    app: heartbeat
    chart: heartbeat-1.2.0
    release: heartbeat
    heritage: Tiller
type: Opaque
data:
  heartbeat.yml: aGVhcnRiZWF0LmNvbmZpZy5tb25pdG9yczoKICBwYXRoOiAvcGF0aC90by9teS9tb25pdG9ycy5kLyoueW1sCiAgcmVsb2FkLmVuYWJsZWQ6IHRydWUKCmhlYXJ0YmVhdC5tb25pdG9yczoKLSB0eXBlOiBodHRwCiAgbmFtZTogRmFpbHVyZSBUZXN0CiAgc2NoZWR1bGU6ICdAZXZlcnkgNXMnCiAgdXJsczogWyJodHRwOi8vbG9jYWxob3N0OjEyMzQ1L3NlcnZpY2Uvc3RhdHVzIl0KICBjaGVjay5yZXNwb25zZS5zdGF0dXM6IDIwMAotIHR5cGU6IGh0dHAKICBuYW1lOiBBU2VydmljZSBQcm9kCiAgc2NoZWR1bGU6ICdAZXZlcnkgNXMnCiAgdXJsczogWyJodHRwczovL2FzZXJ2aWNlLmFsdXRlY2gyNC5jb20vd2ViUG9ydGFsLyJdCiAgY2hlY2sucmVzcG9uc2Uuc3RhdHVzOiAyMDA=
